version: "3.9"
services:
    reverse:
      container_name: reverse
      depends_on:
        - web
        - api
      build: ./proxy
      ports:
        - 80:80
    web:
      container_name: web
      build: ./web
      hostname: blog-web
    api:
      depends_on:
        - db
      environment:
        DBUSER: "${DBUSER}"
        DBPASS: "${DBPASS}"
      container_name: api
      build: ./api
      hostname: blog-api
    db:
      image: mcr.microsoft.com/mssql/server:2022-latest
      hostname: db
      environment:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "${DBPASS}"
      volumes:
        - dbdata:/var/opt/mssql
volumes:
     dbdata: {}
